export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const CREATE_IDEA_SUCCESS = "CREATE_IDEA_SUCCESS";
export const VIEW_IDEAS_SUCCESS = "VIEW_IDEAS_SUCCESS";
export const SUBSCRIBE_IDEA_SUCCESS = "SUBSCRIBE_IDEA_SUCCESS";
export const VIEW_SUBSCRIBE_SUCCESS = "VIEW_SUBSCRIBE_SUCCESS";